#!/bin/bash

# OpenSearch 설치 스크립트

set -e  # 스크립트 실행 중 오류 발생 시 종료
set -u  # 설정되지 않은 변수를 사용하면 오류 처리

# 1. OpenSearch Helm Chart 저장소 추가 및 업데이트
echo "Adding Bitnami Helm repository..."
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

# 2. 기본 values.yaml 파일 다운로드
echo "Downloading default Helm values for OpenSearch..."
helm show values bitnami/opensearch > values.yaml

# 3. OpenSearch 설치
echo "Installing OpenSearch with customized configuration..."
helm install opensearch bitnami/opensearch --namespace opensearch --create-namespace \
#--set security.enabled=true \
#--set security.adminPassword=$PASSWD \
#--set security.tls.restEncryption=true \
#--set security.tls.verificationMode="none" \
--set master.replicaCount=1 \
--set master.persistence.storageClass="nfs-client" \
--set master.networkPolicy.enabled=true \
--set service.type=LoadBalancer \
--set data.replicaCount=3 \
--set data.persistence.storageClass="nfs-client" \
--set data.networkPolicy.enabled=true \
--set coordinating.replicaCount=0 \
--set ingest.enable=false \
--set ingest.replicaCount=0 \
--set dashboards.enabled=true \
--set dashboards.service.type=NodePort \
--set dashboards.service.nodePorts.http=30001 \
--set dashboards.ingress.enabled=true \
--set dashboards.ingress.hostname=opensearch.dashboard.com \
--set dashboards.ingress.ingressClassName="traefik" \
--set dashboards.networkPolicy.enabled=true

echo "OpenSearch installation and configuration completed successfully!"

######################################################################
# 파라미터 설명
######################################################################
# * security.enabled
#   - OpenSearch 보안을 활성화합니다. x-pack 보안 기능을 사용합니다.
#   - 기본값은 false이며, 활성화하지 않으면 계정 인증 기능이 비활성화됩니다.

# * security.adminPassword
#   - OpenSearch admin 계정의 비밀번호를 설정합니다.
#   - Helm 실행 시 --set security.adminPassword=<password> 옵션으로 지정합니다.

# * security.tls.restEncryption
#   - REST API 통신을 암호화합니다.
#   - security.tls.autoGenerated=true로 self-signed TLS 인증서를 생성할 수 있습니다.

# * security.tls.verificationMode
#   - SSL 인증 검증 모드 설정.
#   - "none"으로 설정 시 SSL 검증이 비활성화됩니다.

# * master.replicaCount
#   - Master 노드 복제본의 수를 설정합니다.

# * master.persistence.storageClass
#   - Master 노드의 스토리지 클래스를 지정합니다. 예: "nfs-client".

# * master.networkPolicy.enabled
#   - Master 노드의 네트워크 정책을 활성화합니다.

# * service.type
#   - 클러스터 서비스를 외부에 노출하는 방식. LoadBalancer를 사용하여 외부 접근 가능하게 설정합니다.

# * data.replicaCount
#   - Data 노드 복제본의 수를 설정합니다.

# * data.persistence.storageClass
#   - Data 노드의 스토리지 클래스를 지정합니다. 예: "nfs-client".

# * data.networkPolicy.enabled
#   - Data 노드의 네트워크 정책을 활성화합니다.

# * coordinating.replicaCount
#   - Coordinating 노드 복제본 수를 설정합니다.
#   - Coordinating 노드는 데이터 노드가 최소 10~20개 이상일 때 사용이 권장됩니다.

# * ingest.enable
#   - Ingest 노드 사용 여부를 설정합니다.

# * ingest.replicaCount
#   - Ingest 노드 복제본 수를 설정합니다.

# * dashboards.enabled
#   - OpenSearch Dashboards(시각화 도구) 사용 여부를 설정합니다.

# * dashboards.service.type
#   - Dashboards 서비스를 외부에 노출하는 방식. NodePort를 사용하여 노드에서 접근 가능하게 설정합니다.

# * dashboards.service.nodePorts.http
#   - Dashboards 서비스의 HTTP 포트를 설정합니다. 기본 포트: 30001.

# * dashboards.ingress.enabled
#   - Dashboards에 Ingress를 사용하여 접근할 수 있도록 설정합니다.

# * dashboards.ingress.hostname
#   - Dashboards Ingress를 위한 호스트 이름을 지정합니다. 예: "opensearch.dashboard.com".

# * dashboards.ingress.ingressClassName
#   - Ingress의 ingressClassName을 지정합니다. 예: "traefik".

# * dashboards.networkPolicy.enabled
#   - Dashboards 네트워크 정책을 활성화합니다.
######################################################################
